server:
  port: 8888
  servlet:
    context-path: /api
spring:
  web:
    resources:
      static-locations: classpath:/img/
  mvc:
    static-path-pattern: /img/**

  datasource:
    url: jdbc:mysql://localhost:3306/my_app_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver




mybatis-plus:
  type-aliases-package: cn.niya.api.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl